//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Quan_Ly_Nhan_SuContext : DbContext
    {
        public Quan_Ly_Nhan_SuContext()
            : base("name=Quan_Ly_Nhan_SuContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGCONG> BANGCONG { get; set; }
        public virtual DbSet<BAOHIEM> BAOHIEM { get; set; }
        public virtual DbSet<BOPHAN> BOPHAN { get; set; }
        public virtual DbSet<CONGTY> CONGTY { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<DANTOC> DANTOC { get; set; }
        public virtual DbSet<HOPDONG> HOPDONG { get; set; }
        public virtual DbSet<KHENTHUONG_KYLUAT> KHENTHUONG_KYLUAT { get; set; }
        public virtual DbSet<LOAICA> LOAICA { get; set; }
        public virtual DbSet<LOAICONG> LOAICONG { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<NHANVIEN_PHUCAP> NHANVIEN_PHUCAP { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBAN { get; set; }
        public virtual DbSet<PHUCAP> PHUCAP { get; set; }
        public virtual DbSet<TANGCA> TANGCA { get; set; }
        public virtual DbSet<TONGIAO> TONGIAO { get; set; }
        public virtual DbSet<TRINH_DO> TRINH_DO { get; set; }
        public virtual DbSet<UNGLUONG> UNGLUONG { get; set; }
    }
}
